ALTER TABLE users
ADD COLUMN IF NOT EXISTS role TEXT;

UPDATE users
SET role = 'USER'
WHERE role IS NULL OR TRIM(role) = '';

ALTER TABLE users
ALTER COLUMN role SET DEFAULT 'USER';

ALTER TABLE users
ALTER COLUMN role SET NOT NULL;
