ALTER TABLE institutions
ADD COLUMN IF NOT EXISTS international_phone_number TEXT NULL,
ADD COLUMN IF NOT EXISTS website TEXT NULL,
ADD COLUMN IF NOT EXISTS opening_hours TEXT NULL,
ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION NULL,
ADD COLUMN IF NOT EXISTS user_rating_count INTEGER NULL,
ADD COLUMN IF NOT EXISTS google_maps_url TEXT NULL;
