server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/patify
spring.datasource.username=patify
spring.datasource.password=patify

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true


app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+CHARS_MINIMUM
app.jwt.expiryMinutes=120
