server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ymyowwtzavkiklowchtd
spring.datasource.password=patifyappTeamasko


spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true


app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+CHARS_MINIMUM
app.jwt.expiryMinutes=120

# Add here gemini key kopyala yapıştır.!!!!!!!